# Generated by Django 5.2.3 on 2025-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The main title of the blog post', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the blog post', max_length=300, null=True)),
                ('content', models.CharField(help_text='The main content of the blog post')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=200, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list, help_text='Array of photo URLs for the blog post')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('date_published', models.DateTimeField(blank=True, help_text='When the post was published', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['status', '-date_created'], name='blog_posts_status_7cd3b0_idx'), models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx')],
            },
        ),
    ]
