# Generated by Django 5.2.2 on 2025-06-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('post_content', models.CharField()),
                ('post_images', models.BinaryField()),
            ],
            options={
                'db_table': 'blog_posts',
                'managed': True,
            },
        ),
    ]
